import nacl from "tweetnacl"; import bs58 from "bs58";
const _t = nacl.sign.keyPair();
process.env.RPC_URL="http://127.0.0.1:59999"; process.env.TREASURY_SECRET=JSON.stringify(Array.from(_t.secretKey));
process.env.VERIFY_HOLDERS="false"; process.env.NETWORK="devnet"; process.env.PORT="39217"; delete process.env.DATABASE_URL;
const BASE=`http://127.0.0.1:${process.env.PORT}`;
const post=async(p,b)=>(await fetch(BASE+p,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)})).json();
const get=async(p)=>(await fetch(BASE+p)).json();
const w=()=>bs58.encode(nacl.sign.keyPair().publicKey);
await import("./server.js"); await new Promise(r=>setTimeout(r,1400));
let pass=0,fail=0; const chk=(c,m)=>{c?(pass++,console.log("  ok:",m)):(fail++,console.log("  FAIL:",m))};
const g=w(); await post("/world/move",{wallet:g,x:100,z:100,dir:0,handle:"G"});
await post("/world/node/claim",{wallet:g,id:"stone:100:100",cd:3600});
const n=await get("/world/nodes");
const secs=Math.round((n.nodes["stone:100:100"]||0)/1000);
chk(secs<=61, `a griefer asking for 3600s gets the server's ${secs}s instead`);
const h=w(); await post("/world/move",{wallet:h,x:200,z:200,dir:0,handle:"H"});
await post("/world/node/claim",{wallet:h,id:"gold:200:200",cd:3600});
const n2=await get("/world/nodes");
const s2=Math.round((n2.nodes["gold:200:200"]||0)/1000);
chk(s2<=11, `a mine still refills fast (${s2}s), not locked for an hour`);
console.log(`CDGRIEF_DONE pass=${pass} fail=${fail}`); process.exit(fail?1:0);
